### ISSUE TITLE
AttributeError: 'BertJapaneseTokenizer' object has no attribute 'subword_tokenizer_type'

### ISSUE THREAD

**Issue by EricZhao9482** [ZhaoPeiduo/BLIP2-Japanese#2]
I'm tryna run the example.ipynb file and when i try running load model, I get the error:
AttributeError: 'BertJapaneseTokenizer' object has no attribute 'subword_tokenizer_type'

I have the directories set up from the quickstart guide for pretrained and bert-base-japanese-whole-word-masking

**Comment by ZhaoPeiduo** [comment]
Hi Eric,

I suspect it might be due to an update in the transformer library from huggingface. May I check your transformer library verision? I am working on transformers==4.30.2 with this code base. 

Thanks :)

**Comment by EricZhao9482** [comment]
Thanks for the help! Downgrading it to 4.30.2 got it to work!
